export const chapters = [
  {
    slug: 'welcome',
    number: '序',
    title: 'はじめに',
    description: 'ナロ諸島の地理と、人ともぐの関係。',
    art: 'village',
    tone: 'ochre',
  },
  {
    slug: 'islands',
    number: '一',
    title: 'ナロ諸島',
    description: 'アシロ、トヌ、セラ、ニカ、ウネ、ヨルバの風土と交易。',
    art: 'atlas',
    tone: 'blue',
  },
  {
    slug: 'village',
    number: '二',
    title: '村と島の暮らし',
    description: 'カヤ村の道と日課、六つの島の店や仕事場。',
    art: 'village',
    tone: 'ochre',
  },
  {
    slug: 'mogs',
    number: '三',
    title: 'もぐ図鑑',
    description: '六つの主な種と、島々に暮らす36種の生態。',
    art: 'field-plate',
    tone: 'green',
  },
  {
    slug: 'table',
    number: '四',
    title: '食文化',
    description: '口合わせの習慣、六島の郷土料理、器と道具。',
    art: 'table',
    tone: 'red',
  },
  {
    slug: 'people',
    number: '五',
    title: '登場人物',
    description: 'ミナ、ガロ、サヨ、オル、トキの暮らしと関係。',
    art: 'village',
    tone: 'ochre',
  },
  {
    slug: 'stories',
    number: '六',
    title: '短編',
    description: '六つの島を舞台にした八篇の短編。',
    art: 'winter-night',
    tone: 'blue',
  },
  {
    slug: 'glossary',
    number: '末',
    title: '用語集',
    description: '地名、人名、種名、暮らしに使うことば。',
    art: 'field-plate',
    tone: 'green',
  },
]
