export const chapters = [
  {
    slug: 'welcome',
    number: '序',
    title: 'はじめに',
    subtitle: 'ごはんの向こうに、世界がある。',
    description: '六つの島と、そこに生きる人ともぐ。この旅のはじまりに。',
    art: 'village',
    tone: 'ochre',
  },
  {
    slug: 'islands',
    number: '一',
    title: '島をめぐる',
    subtitle: '海の向こうは、ちがう暮らし。',
    description: '麦の島、森の島、塩の島。帆と櫂をたよりに、ナロ諸島をひとめぐり。',
    art: 'atlas',
    tone: 'blue',
  },
  {
    slug: 'village',
    number: '二',
    title: '暮らしの寄り道',
    subtitle: '坂道を、もう少し先へ。',
    description:
      'カヤ村のかまどから浜へ、そして舟で島の店や古道へ。暮らしの中に、知らなかった寄り道がある。',
    art: 'village',
    tone: 'ochre',
  },
  {
    slug: 'mogs',
    number: '三',
    title: 'もぐを知る',
    subtitle: 'となりにいる、ふしぎな隣人。',
    description: '同じ名前でも、同じじゃない。姿、しぐさ、すみかから、42種の暮らしをのぞく。',
    art: 'field-plate',
    tone: 'green',
  },
  {
    slug: 'table',
    number: '四',
    title: '食卓と暮らし',
    subtitle: 'ひとつの鍋から、それぞれの一皿へ。',
    description: '口合わせ、島の名物、火のそばの仕事。おいしさは、人から人へ、島から島へ。',
    art: 'table',
    tone: 'red',
  },
  {
    slug: 'people',
    number: '五',
    title: '村の人々',
    subtitle: 'あの人のことを、もう少し。',
    description: '器をつくる手、舟を直す手、火を見守る手。ミナを囲む、カヤの日々。',
    art: 'village',
    tone: 'ochre',
  },
  {
    slug: 'stories',
    number: '六',
    title: '島のものがたり',
    subtitle: 'いつもの一日に、小さな物語。',
    description: 'なくした欠片、帰らない舟、夜の足音。ナロに暮らす人ともぐの、八つのお話。',
    art: 'winter-night',
    tone: 'blue',
  },
  {
    slug: 'glossary',
    number: '末',
    title: 'ことばのしおり',
    subtitle: '名前を知ると、景色が変わる。',
    description: '島の名、人の名、食卓のことば。ページの途中で出会った名前を、ここで。',
    art: 'field-plate',
    tone: 'green',
  },
]
