import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
test('expanded catalog searches ingredients and opens a complete recipe', async ({ page }) => {
  await page.goto('/expansion/index.html')
  await expect(page.locator('#recipe-count')).toHaveText('300')
  await expect(page.locator('.card')).toHaveCount(24)
  await page.getByLabel('名前・材料・ことば').fill('トマト')
  await expect(page.locator('.card').first()).toBeVisible()
  await page.locator('.card').first().click()
  await expect(page.getByRole('dialog')).toContainText('材料（1人分）')
  await expect(page.getByRole('dialog')).toContainText('つくり方')
  await expect(page.getByRole('dialog').locator('ol > li').first()).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.getByLabel('名前・材料・ことば').fill('存在しない献立')
  await expect(page.locator('#empty')).toBeVisible()
  await page.getByRole('button', { name: '条件を戻す' }).click()
  await expect(page.locator('.card')).toHaveCount(24)
  await page.getByRole('button', { name: '次へ →' }).click()
  await expect(page.locator('#page-number')).toHaveText('2 / 13')
})
test('character growth, cosmetic preview and mobile layout remain usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/expansion/index.html')
  await page.getByRole('button', { name: 'なかまたち' }).click()
  await expect(page.locator('#result-count')).toContainText('36 種類')
  await page.locator('.card').first().click()
  const adult = await page.locator('.growth-preview').getAttribute('src')
  await page.locator('[data-stage="0"]').click()
  await expect(page.locator('.growth-preview')).not.toHaveAttribute('src', adult!)
  await page.getByRole('button', { name: '閉じる', exact: true }).click()
  await page.getByRole('button', { name: 'きせかえとひろば' }).click()
  await expect(page.locator('#result-count')).toContainText('72 種類')
  await page.getByRole('combobox', { name: '分類', exact: true }).selectOption('hat')
  await page.locator('.card').first().click()
  await expect(page.locator('.tryon .hat')).toBeVisible()
  await page.getByLabel('いっしょに見てみる').selectOption({ index: 1 })
  await expect(page.locator('.tryon .pet')).toBeVisible()
  await page.getByRole('button', { name: '閉じる', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
})
