import type { SpeciesId, GrowthStage, Recipe, Item } from '../game/types'
import { recipes } from './recipes'
export { recipes, legacyRecipes, recipeCategories } from './recipes'

export const species: { id: SpeciesId; name: string; description: string }[] = [
  { id: 'komugi', name: 'こむぎ', description: '食いしんぼうで活発な性格。' },
  { id: 'mame', name: 'まめ', description: '人見知りだが食欲は旺盛。' },
  { id: 'shizuku', name: 'しずく', description: '温かいスープを好む。' },
  { id: 'yuzu', name: 'ゆず', description: '好奇心が強く初めての料理にもよく近づく。' },
  { id: 'momo', name: 'もも', description: 'のんびりした性格で食べるのが遅い。' },
  { id: 'goma', name: 'ごま', description: '夕方になると活発になる。' },
]
export const growthStages: ReadonlyArray<{
  stage: GrowthStage
  name: string
  threshold: number
}> = [
  { stage: 0, name: 'うまれたて', threshold: 0 },
  { stage: 1, name: 'ちびっこ', threshold: 120 },
  { stage: 2, name: 'わんぱく', threshold: 300 },
  { stage: 3, name: 'おとな', threshold: 600 },
  { stage: 4, name: 'とっておき', threshold: 1050 },
]
export function recipeById(id?: string): Recipe | undefined {
  return recipes.find((recipe) => recipe.id === id)
}
export const items: Item[] = [
  {
    id: 'none',
    name: 'ぼうしを外す',
    description: '帽子を外します。',
    kind: 'hat',
    currency: 'coins',
    price: 0,
  },
  {
    id: 'beret',
    name: 'どんぐりベレー',
    description: 'どんぐりをかたどったベレー帽。',
    kind: 'hat',
    currency: 'coins',
    price: 180,
  },
  {
    id: 'sprout',
    name: 'ふたばのかんむり',
    description: '双葉をかたどったかんむり。',
    kind: 'hat',
    currency: 'coins',
    price: 120,
  },
  {
    id: 'chef',
    name: 'コックさんの帽子',
    description: '白いコック帽。',
    kind: 'hat',
    currency: 'gems',
    price: 80,
  },
  {
    id: 'i-picnic-straw',
    name: 'ピクニックの麦わら',
    description: '平たいつばに赤いリボン。遠足の集合写真によく映える。',
    kind: 'hat',
    currency: 'coins',
    price: 80,
    artPath: '/expansion/assets/items/i-picnic-straw.svg',
  },
  {
    id: 'i-wildflower-crown',
    name: '野の花のかんむり',
    description: '白い花と黄いろい花を交互に編んだ、小さな輪。',
    kind: 'hat',
    currency: 'coins',
    price: 135,
    artPath: '/expansion/assets/items/i-wildflower-crown.svg',
  },
  {
    id: 'i-ladybird-cap',
    name: 'てんとう虫キャップ',
    description: '丸い羽の継ぎ目まで描いた、赤いてんとう虫の帽子。',
    kind: 'hat',
    currency: 'coins',
    price: 190,
    artPath: '/expansion/assets/items/i-ladybird-cap.svg',
  },
  {
    id: 'i-mushroom-cap',
    name: 'きのこ帽',
    description: '赤い傘に白い斑点。つばの下にはきのこのひだ。',
    kind: 'hat',
    currency: 'coins',
    price: 115,
    artPath: '/expansion/assets/items/i-mushroom-cap.svg',
  },
  {
    id: 'i-sailor-knot',
    name: '水兵さんの帽子',
    description: '青い帯と錨のワッペンがついた、折り返しのある水兵帽。',
    kind: 'hat',
    currency: 'coins',
    price: 150,
    artPath: '/expansion/assets/items/i-sailor-knot.svg',
  },
  {
    id: 'i-moon-wizard',
    name: '三日月のとんがり帽',
    description: '折れた先に三日月がぶら下がる、夜空色の帽子。',
    kind: 'hat',
    currency: 'coins',
    price: 255,
    artPath: '/expansion/assets/items/i-moon-wizard.svg',
  },
  {
    id: 'neck-none',
    name: 'くびもとを外す',
    description: 'くびもとの飾りを外します。',
    kind: 'neck',
    currency: 'coins',
    price: 0,
  },
  {
    id: 'neck-bandana',
    name: '赤いバンダナ',
    description: 'おさんぽにぴったりの、赤い三角バンダナ。',
    kind: 'neck',
    currency: 'coins',
    price: 100,
  },
  {
    id: 'neck-bow',
    name: 'おめかしリボン',
    description: 'くびもとで結んだ、晴れの日のリボン。',
    kind: 'neck',
    currency: 'coins',
    price: 160,
  },
  {
    id: 'neck-scarf',
    name: 'しましまマフラー',
    description: 'ふんわり巻ける、しま模様のマフラー。',
    kind: 'neck',
    currency: 'coins',
    price: 240,
  },
  {
    id: 'neck-shell',
    name: '貝がらペンダント',
    description: '浜辺で見つけた貝がらのペンダント。',
    kind: 'neck',
    currency: 'gems',
    price: 60,
  },
  {
    id: 'bag-none',
    name: 'かばんを外す',
    description: 'かばんを外します。',
    kind: 'bag',
    currency: 'coins',
    price: 0,
  },
  {
    id: 'bag-satchel',
    name: 'おさんぽポシェット',
    description: '小さなたからものをしまえるポシェット。',
    kind: 'bag',
    currency: 'coins',
    price: 200,
  },
  {
    id: 'bag-basket',
    name: 'ピクニックかご',
    description: 'おべんとうを詰めた、編み目のかご。',
    kind: 'bag',
    currency: 'coins',
    price: 280,
  },
  {
    id: 'bag-acorn',
    name: 'どんぐりポーチ',
    description: 'ころんと丸い、どんぐり形のポーチ。',
    kind: 'bag',
    currency: 'coins',
    price: 180,
  },
  {
    id: 'bag-star',
    name: '星くずバッグ',
    description: 'きらりと星を飾った、夜空色のバッグ。',
    kind: 'bag',
    currency: 'gems',
    price: 90,
  },
  {
    id: 'plain',
    name: 'いつものひろば',
    description: '最初のひろば。',
    kind: 'room',
    currency: 'coins',
    price: 0,
  },
  {
    id: 'garden',
    name: '木もれびのひろば',
    description: '大きな木の枝葉から、やわらかな光が差すひろば。',
    kind: 'room',
    currency: 'gems',
    price: 100,
  },
  {
    id: 'night',
    name: '星あかりのひろば',
    description: '星空が見える夜のひろば。',
    kind: 'room',
    currency: 'gems',
    price: 120,
  },
  {
    id: 'seaside',
    name: '夕なぎの浜辺',
    description: '夕焼けの海と、波が寄せる砂浜。',
    kind: 'room',
    currency: 'coins',
    price: 320,
  },
  {
    id: 'brook',
    name: '小川のほとり',
    description: 'せせらぎに木の橋がかかる、緑のほとり。',
    kind: 'room',
    currency: 'coins',
    price: 280,
  },
  {
    id: 'greenhouse',
    name: '温室のひろば',
    description: 'ガラス屋根の下で、草花に囲まれるひろば。',
    kind: 'room',
    currency: 'gems',
    price: 140,
  },
]
