import type { FoodGroup } from '../meals/types'

export const dishCategories = {
  rice: 'ごはん・丼',
  noodles: '麺',
  bread: 'パン・粉もの・シリアル',
  meat: '肉のおかず',
  seafood: '魚介のおかず',
  egg_soy: '卵・豆腐・豆',
  vegetables: '野菜・副菜',
  soup_hotpot: '汁物・鍋',
  sweets: 'おやつ・果物',
  other: 'その他のおかず',
} as const

export type DishCategory = keyof typeof dishCategories

/** Broad meal classifications do not grant collectible recipe cards. */
export type GenericDish = {
  id: string
  name: string
  category: DishCategory
  aliases: readonly string[]
  sample: 'rice' | 'pasta' | 'curry' | 'soup'
  description: string
  /** Named foods only; these suggestions do not establish portions or nutrient adequacy. */
  suggestedGroups: readonly FoodGroup[]
  artPath?: string
}

export const genericDishes: GenericDish[] = [
  {
    id: 'generic-pasta',
    name: 'パスタ',
    category: 'noodles',
    aliases: ['ぱすた', 'スパゲッティ', 'スパゲティ'],
    sample: 'pasta',
    description: 'ソースや具材を問わないパスタ。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-curry',
    name: 'カレー',
    category: 'rice',
    aliases: ['かれー', 'カレーライス', '咖喱'],
    sample: 'curry',
    description: '具材や味付けを問わないカレー。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-fried-rice',
    name: 'チャーハン',
    category: 'rice',
    aliases: ['ちゃーはん', '炒飯', '炒めご飯'],
    sample: 'rice',
    description: 'ごはんと具材を炒めた料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-hamburg',
    name: 'ハンバーグ',
    category: 'meat',
    aliases: ['はんばーぐ', 'ハンバーグステーキ'],
    sample: 'rice',
    description: 'ソースや付け合わせを問わないハンバーグ。',
    suggestedGroups: ['protein'],
    artPath: '/expansion/assets/recipes/r-onion-hamburg-steak.svg',
  },
  {
    id: 'generic-onigiri',
    name: 'おにぎり',
    category: 'rice',
    aliases: ['おむすび', '握り飯'],
    sample: 'rice',
    description: '具材や形を問わないおにぎり。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-donburi',
    name: '丼もの',
    category: 'rice',
    aliases: ['どんぶり', '丼物', 'どんもの'],
    sample: 'rice',
    description: 'ごはんの上に具材をのせた丼もの。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-udon',
    name: 'うどん',
    category: 'noodles',
    aliases: ['饂飩', 'かけうどん', 'ざるうどん'],
    sample: 'pasta',
    description: 'つゆや具材を問わないうどん。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-soba',
    name: 'そば',
    category: 'noodles',
    aliases: ['蕎麦', '日本そば', 'かけそば', 'ざるそば'],
    sample: 'pasta',
    description: 'つゆや具材を問わないそば。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-ramen',
    name: 'ラーメン',
    category: 'noodles',
    aliases: ['らーめん', 'らあめん', '中華そば', '拉麺'],
    sample: 'pasta',
    description: 'スープや具材を問わないラーメン。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-yakisoba',
    name: '焼きそば',
    category: 'noodles',
    aliases: ['やきそば', '焼そば'],
    sample: 'pasta',
    description: '味付けや具材を問わない焼きそば。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-soup',
    name: 'スープ',
    category: 'soup_hotpot',
    aliases: ['すーぷ', '汁物'],
    sample: 'soup',
    description: '具材や味付けを問わないスープ。',
    suggestedGroups: [],
  },
  {
    id: 'generic-miso-soup',
    name: 'みそ汁',
    category: 'soup_hotpot',
    aliases: ['みそしる', '味噌汁', '味噌しる', 'お味噌汁'],
    sample: 'soup',
    description: '具材を問わないみそ汁。',
    suggestedGroups: [],
  },
  {
    id: 'generic-salad',
    name: 'サラダ',
    category: 'vegetables',
    aliases: ['さらだ', '野菜サラダ', 'グリーンサラダ'],
    sample: 'rice',
    description: '野菜や具材を盛り合わせたサラダ。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-stir-fry',
    name: '炒め物',
    category: 'other',
    aliases: ['いためもの', '炒めもの', '炒物'],
    sample: 'rice',
    description: '肉や野菜などを炒めた料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-stew',
    name: '煮物',
    category: 'other',
    aliases: ['にもの', '煮もの'],
    sample: 'soup',
    description: '肉や魚、野菜などを煮た料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-grilled-fish',
    name: '焼き魚',
    category: 'seafood',
    aliases: ['やきざかな', '焼魚'],
    sample: 'rice',
    description: '魚の種類や味付けを問わない焼き魚。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-plain-rice',
    name: '白ごはん',
    category: 'rice',
    aliases: ['しろごはん', '白ご飯', 'ごはん', 'ご飯', '白米', 'ライス'],
    sample: 'rice',
    description: 'おかずをのせずに盛ったごはん。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-brown-rice',
    name: '玄米・雑穀ごはん',
    category: 'rice',
    aliases: ['げんまい', 'ざっこくごはん', '玄米ご飯', '雑穀米', 'もち麦ご飯'],
    sample: 'rice',
    description: '玄米や雑穀を炊いたごはん。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-omelet-rice',
    name: 'オムライス',
    category: 'rice',
    aliases: ['おむらいす'],
    sample: 'rice',
    description: '炒めたごはんを卵で包む、または卵をのせた料理。',
    suggestedGroups: ['staple', 'protein'],
  },
  {
    id: 'generic-hayashi-rice',
    name: 'ハヤシライス',
    category: 'rice',
    aliases: ['はやしらいす', 'ハッシュドビーフライス'],
    sample: 'curry',
    description: '牛肉などを洋風のソースで煮て、ごはんにかけた料理。',
    suggestedGroups: ['staple', 'protein'],
  },
  {
    id: 'generic-keema-curry',
    name: 'キーマカレー',
    category: 'rice',
    aliases: ['きーまかれー', 'ひき肉カレー'],
    sample: 'curry',
    description: 'ひき肉を使ったカレーとごはん。',
    suggestedGroups: ['staple', 'protein'],
  },
  {
    id: 'generic-dry-curry',
    name: 'ドライカレー',
    category: 'rice',
    aliases: ['どらいかれー', 'カレーチャーハン'],
    sample: 'curry',
    description: '汁気の少ないカレー、またはカレー味の炒めごはん。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-sushi',
    name: '寿司',
    category: 'rice',
    aliases: ['すし', 'お寿司', 'おすし', '鮨', '握り寿司', 'にぎりずし'],
    sample: 'rice',
    description: '酢飯と具材を組み合わせた寿司。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-chirashi-sushi',
    name: 'ちらし寿司',
    category: 'rice',
    aliases: ['ちらしずし', 'ちらし寿し', 'ばら寿司', '五目寿司'],
    sample: 'rice',
    description: '酢飯に具材を混ぜたり散らしたりした寿司。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-inari-sushi',
    name: 'いなり寿司',
    category: 'rice',
    aliases: ['いなりずし', 'おいなりさん', '稲荷寿司'],
    sample: 'rice',
    description: '甘辛く煮た油揚げに酢飯を詰めた寿司。',
    suggestedGroups: ['staple', 'protein'],
  },
  {
    id: 'generic-sushi-roll',
    name: '巻き寿司',
    category: 'rice',
    aliases: ['まきずし', '巻きずし', '海苔巻き', 'のりまき', '太巻き', '細巻き'],
    sample: 'rice',
    description: '酢飯と具材を海苔などで巻いた寿司。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-takikomi-rice',
    name: '炊き込みごはん',
    category: 'rice',
    aliases: ['たきこみごはん', '炊き込みご飯', '五目ごはん', 'かやくご飯'],
    sample: 'rice',
    description: '具材と調味料を米と一緒に炊いたごはん。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-mazegohan',
    name: '混ぜごはん',
    category: 'rice',
    aliases: ['まぜごはん', '混ぜご飯', 'まぜご飯'],
    sample: 'rice',
    description: '炊いたごはんに具材を混ぜた料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-pilaf',
    name: 'ピラフ',
    category: 'rice',
    aliases: ['ぴらふ'],
    sample: 'rice',
    description: '米を炒めてからスープで炊く洋風のごはん。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-risotto',
    name: 'リゾット',
    category: 'rice',
    aliases: ['りぞっと'],
    sample: 'rice',
    description: '米をスープで煮た、しっとりしたごはん料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-doria',
    name: 'ドリア',
    category: 'rice',
    aliases: ['どりあ'],
    sample: 'rice',
    description: 'ごはんにソースをかけてオーブンで焼いた料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-porridge',
    name: 'おかゆ',
    category: 'rice',
    aliases: ['お粥', 'かゆ', '粥'],
    sample: 'rice',
    description: '米を多めの水で柔らかく炊いた料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-zosui',
    name: '雑炊',
    category: 'rice',
    aliases: ['ぞうすい', 'おじや'],
    sample: 'rice',
    description: 'だしやスープにごはんを入れて煮た料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-ochazuke',
    name: 'お茶漬け',
    category: 'rice',
    aliases: ['おちゃづけ', '茶漬け', 'ちゃづけ'],
    sample: 'rice',
    description: 'ごはんにお茶やだしをかけた料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-egg-over-rice',
    name: '卵かけごはん',
    category: 'rice',
    aliases: ['たまごかけごはん', '卵かけご飯', 'たまごかけご飯', 'TKG'],
    sample: 'rice',
    description: 'ごはんに生卵をからめた料理。',
    suggestedGroups: ['staple', 'protein'],
  },
  {
    id: 'generic-gyudon',
    name: '牛丼',
    category: 'rice',
    aliases: ['ぎゅうどん'],
    sample: 'rice',
    description: '煮た牛肉をごはんにのせた丼。',
    suggestedGroups: ['staple', 'protein'],
  },
  {
    id: 'generic-oyakodon',
    name: '親子丼',
    category: 'rice',
    aliases: ['おやこどん'],
    sample: 'rice',
    description: '鶏肉と卵をごはんにのせた丼。',
    suggestedGroups: ['staple', 'protein'],
  },
  {
    id: 'generic-katsudon',
    name: 'カツ丼',
    category: 'rice',
    aliases: ['かつどん', 'かつ丼', 'ソースカツ丼'],
    sample: 'rice',
    description: 'カツをごはんにのせた丼。',
    suggestedGroups: ['staple', 'protein'],
  },
  {
    id: 'generic-pork-rice-bowl',
    name: '豚丼',
    category: 'rice',
    aliases: ['ぶたどん', 'とんどん'],
    sample: 'rice',
    description: '焼いたり煮たりした豚肉をごはんにのせた丼。',
    suggestedGroups: ['staple', 'protein'],
  },
  {
    id: 'generic-tendon',
    name: '天丼',
    category: 'rice',
    aliases: ['てんどん', '天ぷら丼'],
    sample: 'rice',
    description: '天ぷらをごはんにのせ、たれをかけた丼。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-seafood-rice-bowl',
    name: '海鮮丼',
    category: 'rice',
    aliases: ['かいせんどん', '刺身丼', '鉄火丼', 'ねぎとろ丼'],
    sample: 'rice',
    description: '刺身などの魚介をごはんにのせた丼。',
    suggestedGroups: ['staple', 'protein'],
  },
  {
    id: 'generic-eel-rice-bowl',
    name: 'うな丼・うな重',
    category: 'rice',
    aliases: ['うなどん', 'うなじゅう', '鰻丼', '鰻重'],
    sample: 'rice',
    description: 'うなぎの蒲焼きをごはんにのせた料理。',
    suggestedGroups: ['staple', 'protein'],
  },
  {
    id: 'generic-bibimbap',
    name: 'ビビンバ',
    category: 'rice',
    aliases: ['びびんば', 'ビビンパ', '石焼ビビンバ'],
    sample: 'rice',
    description: 'ごはんにナムルなどの具材をのせ、混ぜて食べる料理。',
    suggestedGroups: ['staple', 'vegetable'],
  },
  {
    id: 'generic-taco-rice',
    name: 'タコライス',
    category: 'rice',
    aliases: ['たこらいす'],
    sample: 'rice',
    description: 'ごはんに味付けしたひき肉と生野菜をのせた料理。',
    suggestedGroups: ['staple', 'protein', 'vegetable'],
  },
  {
    id: 'generic-natto-rice',
    name: '納豆ごはん',
    category: 'rice',
    aliases: ['なっとうごはん', '納豆ご飯', '納豆かけごはん'],
    sample: 'rice',
    description: 'ごはんに納豆をのせた料理。',
    suggestedGroups: ['staple', 'protein'],
  },
  {
    id: 'generic-mochi',
    name: '餅',
    category: 'rice',
    aliases: ['もち', 'お餅', 'おもち', '焼き餅', '切り餅'],
    sample: 'rice',
    description: 'もち米などをついて作った餅を、焼く・煮るなどした料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-somen',
    name: 'そうめん',
    category: 'noodles',
    aliases: ['素麺', 'そーめん', '冷やしそうめん'],
    sample: 'pasta',
    description: '細い小麦の麺をゆで、つゆなどで食べる料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-nyumen',
    name: 'にゅうめん',
    category: 'noodles',
    aliases: ['煮麺', '温かいそうめん'],
    sample: 'pasta',
    description: 'そうめんを温かい汁で食べる料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-cold-ramen',
    name: '冷やし中華',
    category: 'noodles',
    aliases: ['ひやしちゅうか', '冷し中華'],
    sample: 'pasta',
    description: '冷たい中華麺に具材とたれをかけた料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-tsukemen',
    name: 'つけ麺',
    category: 'noodles',
    aliases: ['つけめん', '付け麺'],
    sample: 'pasta',
    description: '中華麺を別の器のつけ汁につけて食べる料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-mazesoba',
    name: 'まぜそば・油そば',
    category: 'noodles',
    aliases: ['まぜそば', '油そば', 'あぶらそば', '混ぜそば', '汁なしラーメン'],
    sample: 'pasta',
    description: '汁の少ない中華麺を、たれや油と混ぜて食べる料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-tantanmen',
    name: '担々麺',
    category: 'noodles',
    aliases: ['たんたんめん', 'タンタンメン', '担担麺'],
    sample: 'pasta',
    description: 'ごまや香辛料を使ったたれ・スープの中華麺。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-champon',
    name: 'ちゃんぽん',
    category: 'noodles',
    aliases: ['チャンポン', '長崎ちゃんぽん'],
    sample: 'pasta',
    description: '太めの中華麺と具材をスープで煮た料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-sara-udon',
    name: '皿うどん',
    category: 'noodles',
    aliases: ['さらうどん', '長崎皿うどん'],
    sample: 'pasta',
    description: '麺に具材入りのあんをかけた料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-yaki-udon',
    name: '焼きうどん',
    category: 'noodles',
    aliases: ['やきうどん', '焼うどん'],
    sample: 'pasta',
    description: 'うどんと具材を炒めた料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-curry-udon',
    name: 'カレーうどん',
    category: 'noodles',
    aliases: ['かれーうどん'],
    sample: 'pasta',
    description: 'うどんにカレー味の汁を合わせた料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-napolitan',
    name: 'ナポリタン',
    category: 'noodles',
    aliases: ['なぽりたん', 'スパゲッティナポリタン'],
    sample: 'pasta',
    description: 'ケチャップで味付けして炒めたパスタ。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-meat-sauce-pasta',
    name: 'ミートソースパスタ',
    category: 'noodles',
    aliases: ['みーとそーすぱすた', 'ミートソーススパゲッティ', 'ボロネーゼ'],
    sample: 'pasta',
    description: 'ひき肉入りのソースをからめたパスタ。',
    suggestedGroups: ['staple', 'protein'],
  },
  {
    id: 'generic-carbonara',
    name: 'カルボナーラ',
    category: 'noodles',
    aliases: ['かるぼなーら'],
    sample: 'pasta',
    description: '卵とチーズを使ったソースのパスタ。',
    suggestedGroups: ['staple', 'protein', 'dairy'],
  },
  {
    id: 'generic-peperoncino',
    name: 'ペペロンチーノ',
    category: 'noodles',
    aliases: ['ぺぺろんちーの', 'アーリオオーリオ'],
    sample: 'pasta',
    description: 'にんにくと唐辛子をきかせたオイルのパスタ。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-udon-hotpot',
    name: '煮込みうどん',
    category: 'noodles',
    aliases: ['にこみうどん', '鍋焼きうどん', 'なべやきうどん', '味噌煮込みうどん'],
    sample: 'pasta',
    description: 'うどんを具材と一緒に鍋で煮た料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-pho',
    name: 'フォー',
    category: 'noodles',
    aliases: ['ふぉー'],
    sample: 'pasta',
    description: '平たい米の麺をスープなどで食べる料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-bifun',
    name: 'ビーフン',
    category: 'noodles',
    aliases: ['びーふん', '焼きビーフン'],
    sample: 'pasta',
    description: '細い米の麺を炒めたり汁に入れたりした料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-bread',
    name: 'パン',
    category: 'bread',
    aliases: ['ぱん', '菓子パン', '調理パン'],
    sample: 'rice',
    description: '種類や具材を問わないパン。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-plain-bread',
    name: '食パン・トースト',
    category: 'bread',
    aliases: ['しょくぱん', 'とーすと', '食パン', 'トースト'],
    sample: 'rice',
    description: '切った食パン、または焼いた食パン。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-bread-roll',
    name: 'ロールパン',
    category: 'bread',
    aliases: ['ろーるぱん', 'バターロール', 'テーブルロール'],
    sample: 'rice',
    description: '小さく丸めて焼いたパン。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-croissant',
    name: 'クロワッサン',
    category: 'bread',
    aliases: ['くろわっさん'],
    sample: 'rice',
    description: '生地を重ねて焼いた、層のあるパン。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-baguette',
    name: 'フランスパン',
    category: 'bread',
    aliases: ['ふらんすぱん', 'バゲット', 'バタール'],
    sample: 'rice',
    description: '皮が硬く、かみ応えのあるパン。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-sandwich',
    name: 'サンドイッチ',
    category: 'bread',
    aliases: ['さんどいっち', 'サンドウィッチ', 'サンド'],
    sample: 'rice',
    description: 'パンに具材をはさんだ料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-hot-sandwich',
    name: 'ホットサンド',
    category: 'bread',
    aliases: ['ほっとさんど', '焼きサンド'],
    sample: 'rice',
    description: '具材をはさんだパンを押し焼きにした料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-hamburger',
    name: 'ハンバーガー',
    category: 'bread',
    aliases: ['はんばーがー', 'バーガー'],
    sample: 'rice',
    description: '丸いパンにパティなどの具材をはさんだ料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-hot-dog',
    name: 'ホットドッグ',
    category: 'bread',
    aliases: ['ほっとどっぐ', 'ホットドック'],
    sample: 'rice',
    description: '細長いパンにソーセージをはさんだ料理。',
    suggestedGroups: ['staple', 'protein'],
  },
  {
    id: 'generic-pizza',
    name: 'ピザ',
    category: 'bread',
    aliases: ['ぴざ', 'ピッツァ'],
    sample: 'rice',
    description: '平たい生地にソースや具材をのせて焼いた料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-french-toast',
    name: 'フレンチトースト',
    category: 'bread',
    aliases: ['ふれんちとーすと'],
    sample: 'rice',
    description: '食パンを卵液などに浸して焼いた料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-pancakes',
    name: 'パンケーキ',
    category: 'bread',
    aliases: ['ぱんけーき', 'ホットケーキ', 'ほっとけーき'],
    sample: 'rice',
    description: '小麦粉などの生地を丸く平らに焼いた料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-okonomiyaki',
    name: 'お好み焼き',
    category: 'bread',
    aliases: ['おこのみやき', 'お好み焼', '広島焼き'],
    sample: 'rice',
    description: 'キャベツなどを小麦粉の生地と合わせて焼いた料理。',
    suggestedGroups: ['staple', 'vegetable'],
  },
  {
    id: 'generic-takoyaki',
    name: 'たこ焼き',
    category: 'bread',
    aliases: ['たこやき', 'タコ焼き', 'たこ焼'],
    sample: 'rice',
    description: 'たこを入れた生地を丸く焼いた料理。',
    suggestedGroups: ['staple', 'protein'],
  },
  {
    id: 'generic-chijimi',
    name: 'チヂミ',
    category: 'bread',
    aliases: ['ちぢみ', 'チジミ', '韓国風お好み焼き'],
    sample: 'rice',
    description: '小麦粉などの生地に具材を混ぜ、薄く焼いた料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-nikuman',
    name: '肉まん',
    category: 'bread',
    aliases: ['にくまん', '豚まん', 'ぶたまん'],
    sample: 'rice',
    description: '肉入りのあんを生地で包んで蒸した料理。',
    suggestedGroups: ['staple', 'protein'],
  },
  {
    id: 'generic-bagel',
    name: 'ベーグル',
    category: 'bread',
    aliases: ['べーぐる'],
    sample: 'rice',
    description: '輪の形をした、かみ応えのあるパン。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-cereal',
    name: 'シリアル',
    category: 'bread',
    aliases: ['しりある', 'コーンフレーク', 'グラノーラ', 'ミューズリー'],
    sample: 'rice',
    description: '穀物を焼くなどして加工した朝食向けの食品。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-oatmeal',
    name: 'オートミール',
    category: 'bread',
    aliases: ['おーとみーる', 'オーツ粥'],
    sample: 'rice',
    description: '加工したオーツ麦を、水などで煮たりふやかしたりした料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-karaage',
    name: '唐揚げ',
    category: 'meat',
    aliases: ['からあげ', 'から揚げ', '鶏の唐揚げ', '鶏唐揚げ'],
    sample: 'rice',
    description: '味付けした鶏肉に粉をまぶして揚げた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-tonkatsu',
    name: 'とんかつ',
    category: 'meat',
    aliases: ['トンカツ', '豚カツ', '豚かつ', 'ヒレカツ', 'ロースカツ'],
    sample: 'rice',
    description: '豚肉にパン粉をつけて揚げた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-chicken-katsu',
    name: 'チキンカツ',
    category: 'meat',
    aliases: ['ちきんかつ', '鶏カツ', 'とりかつ'],
    sample: 'rice',
    description: '鶏肉にパン粉をつけて揚げた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-menchi-katsu',
    name: 'メンチカツ',
    category: 'meat',
    aliases: ['めんちかつ', 'ミンチカツ'],
    sample: 'rice',
    description: 'ひき肉のたねにパン粉をつけて揚げた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-korokke',
    name: 'コロッケ',
    category: 'other',
    aliases: ['ころっけ', 'ポテトコロッケ', 'クリームコロッケ'],
    sample: 'rice',
    description: 'つぶしたいもやソースなどを衣で包んで揚げた料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-gyoza',
    name: '餃子',
    category: 'meat',
    aliases: ['ぎょうざ', 'ギョーザ', 'ギョウザ', '焼き餃子', '水餃子'],
    sample: 'rice',
    description: '薄い皮で肉や野菜などのあんを包み、焼いたりゆでたりした料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-shumai',
    name: '焼売',
    category: 'meat',
    aliases: ['しゅうまい', 'シュウマイ', 'シューマイ'],
    sample: 'rice',
    description: 'あんを薄い皮で包み、蒸した料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-spring-roll',
    name: '春巻き',
    category: 'meat',
    aliases: ['はるまき', '春巻'],
    sample: 'rice',
    description: '具材を薄い皮で巻いて揚げた料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-yakiniku',
    name: '焼肉',
    category: 'meat',
    aliases: ['やきにく', '焼き肉'],
    sample: 'rice',
    description: '薄切り肉などを焼いて、たれや塩で食べる料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-steak',
    name: 'ステーキ',
    category: 'meat',
    aliases: ['すてーき', 'ビーフステーキ', 'サーロインステーキ'],
    sample: 'rice',
    description: '厚めに切った肉を焼いた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-roast-beef',
    name: 'ローストビーフ',
    category: 'meat',
    aliases: ['ろーすとびーふ'],
    sample: 'rice',
    description: '牛肉のかたまりを焼き、薄く切った料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-pork-ginger',
    name: '豚のしょうが焼き',
    category: 'meat',
    aliases: ['ぶたのしょうがやき', '生姜焼き', 'しょうが焼き', '豚の生姜焼き'],
    sample: 'rice',
    description: '豚肉をしょうがのきいたたれで焼いた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-chicken-teriyaki',
    name: '鶏の照り焼き',
    category: 'meat',
    aliases: ['とりのてりやき', '照り焼きチキン', 'てりやきちきん'],
    sample: 'rice',
    description: '鶏肉に甘辛いたれをからめて焼いた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-yakitori',
    name: '焼き鳥',
    category: 'meat',
    aliases: ['やきとり', '焼鳥'],
    sample: 'rice',
    description: '鶏肉などを串に刺して焼いた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-steamed-chicken',
    name: '蒸し鶏',
    category: 'meat',
    aliases: ['むしどり', 'サラダチキン', 'ゆで鶏', '茹で鶏'],
    sample: 'rice',
    description: '鶏肉を蒸す・ゆでるなどして火を通した料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-bang-bang-chicken',
    name: '棒棒鶏',
    category: 'meat',
    aliases: ['ばんばんじー', 'バンバンジー'],
    sample: 'rice',
    description: '蒸した鶏肉などにごまだれをかけた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-meatballs',
    name: '肉団子',
    category: 'meat',
    aliases: ['にくだんご', 'ミートボール', 'みーとぼーる'],
    sample: 'rice',
    description: 'ひき肉を丸めて焼く・煮るなどした料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-nikujaga',
    name: '肉じゃが',
    category: 'meat',
    aliases: ['にくじゃが'],
    sample: 'rice',
    description: '肉とじゃがいもなどを甘辛く煮た料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-pork-belly-stew',
    name: '豚の角煮',
    category: 'meat',
    aliases: ['ぶたのかくに', '角煮', 'かくに'],
    sample: 'rice',
    description: '厚切りの豚肉を柔らかく煮た料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-sweet-sour-pork',
    name: '酢豚',
    category: 'meat',
    aliases: ['すぶた'],
    sample: 'rice',
    description: '豚肉などに甘酢あんをからめた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-twice-cooked-pork',
    name: '回鍋肉',
    category: 'meat',
    aliases: ['ほいこーろー', 'ホイコーロー', 'ホイコウロウ'],
    sample: 'rice',
    description: '豚肉とキャベツなどをみそ風味で炒めた料理。',
    suggestedGroups: ['protein', 'vegetable'],
  },
  {
    id: 'generic-pepper-steak',
    name: '青椒肉絲',
    category: 'meat',
    aliases: ['ちんじゃおろーす', 'チンジャオロース', 'チンジャオロウス'],
    sample: 'rice',
    description: '細切り肉とピーマンなどを炒めた料理。',
    suggestedGroups: ['protein', 'vegetable'],
  },
  {
    id: 'generic-sausage',
    name: 'ソーセージ・ウインナー',
    category: 'meat',
    aliases: [
      'そーせーじ',
      'ういんなー',
      'ソーセージ',
      'ウインナー',
      'ウィンナー',
      'フランクフルト',
    ],
    sample: 'rice',
    description: '腸詰めにした肉を焼く・ゆでるなどした料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-chicken-nanban',
    name: 'チキン南蛮',
    category: 'meat',
    aliases: ['ちきんなんばん'],
    sample: 'rice',
    description: '揚げた鶏肉に甘酢をからめ、タルタルソースなどを添えた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-meat-vegetable-stir-fry',
    name: '肉野菜炒め',
    category: 'meat',
    aliases: ['にくやさいいため'],
    sample: 'rice',
    description: '肉と野菜を一緒に炒めた料理。',
    suggestedGroups: ['protein', 'vegetable'],
  },
  {
    id: 'generic-meat-saute',
    name: '肉のソテー',
    category: 'meat',
    aliases: ['にくのそてー', 'チキンソテー', 'ポークソテー', '鶏肉のソテー', '豚肉のソテー'],
    sample: 'rice',
    description: '鶏肉や豚肉などをフライパンで焼いた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-sashimi',
    name: '刺身',
    category: 'seafood',
    aliases: ['さしみ', 'お刺身', 'お造り', 'おつくり'],
    sample: 'rice',
    description: '生の魚介を切って盛り付けた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-simmered-fish',
    name: '煮魚',
    category: 'seafood',
    aliases: ['にざかな', '魚の煮付け', '煮付け'],
    sample: 'rice',
    description: '魚を煮汁で煮た料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-saba-miso',
    name: 'さばのみそ煮',
    category: 'seafood',
    aliases: ['さばのみそに', '鯖の味噌煮', 'サバの味噌煮', 'さば味噌'],
    sample: 'rice',
    description: 'さばをみそ味の煮汁で煮た料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-fish-teriyaki',
    name: '魚の照り焼き',
    category: 'seafood',
    aliases: ['さかなのてりやき', 'ぶりの照り焼き', 'ブリ照り'],
    sample: 'rice',
    description: '魚に甘辛いたれをからめて焼いた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-fish-meuniere',
    name: '魚のムニエル',
    category: 'seafood',
    aliases: ['さかなのむにえる', 'ムニエル', '鮭のムニエル'],
    sample: 'rice',
    description: '魚に粉をまぶし、バターなどで焼いた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-fish-foil-bake',
    name: '魚のホイル焼き',
    category: 'seafood',
    aliases: ['さかなのほいるやき', '鮭のホイル焼き', 'ホイル焼き'],
    sample: 'rice',
    description: '魚や具材をアルミホイルで包んで蒸し焼きにした料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-fish-fry',
    name: '魚のフライ',
    category: 'seafood',
    aliases: ['さかなのふらい', '白身魚フライ', 'アジフライ', 'あじふらい'],
    sample: 'rice',
    description: '魚にパン粉をつけて揚げた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-shrimp-fry',
    name: 'エビフライ',
    category: 'seafood',
    aliases: ['えびふらい', '海老フライ'],
    sample: 'rice',
    description: 'えびにパン粉をつけて揚げた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-fried-oyster',
    name: 'カキフライ',
    category: 'seafood',
    aliases: ['かきふらい', '牡蠣フライ'],
    sample: 'rice',
    description: 'かきにパン粉をつけて揚げた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-shrimp-chili',
    name: 'エビチリ',
    category: 'seafood',
    aliases: ['えびちり', '海老チリ', 'えびのチリソース'],
    sample: 'rice',
    description: 'えびに辛みのある赤いソースをからめた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-shrimp-mayo',
    name: 'エビマヨ',
    category: 'seafood',
    aliases: ['えびまよ', '海老マヨ'],
    sample: 'rice',
    description: 'えびにマヨネーズ風味のソースをからめた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-carpaccio',
    name: 'カルパッチョ',
    category: 'other',
    aliases: ['かるぱっちょ'],
    sample: 'rice',
    description: '薄切りの魚介などに油や調味料をかけた料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-seafood-nanbanzuke',
    name: '魚の南蛮漬け',
    category: 'seafood',
    aliases: ['さかなのなんばんづけ', '南蛮漬け', 'なんばんづけ', 'あじの南蛮漬け'],
    sample: 'rice',
    description: '揚げた魚を野菜と一緒に甘酢へ漬けた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-clam-sake-steam',
    name: 'あさりの酒蒸し',
    category: 'seafood',
    aliases: ['あさりのさかむし', '浅蜊の酒蒸し'],
    sample: 'rice',
    description: 'あさりを酒で蒸した料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-aquapazza',
    name: 'アクアパッツァ',
    category: 'seafood',
    aliases: ['あくあぱっつぁ'],
    sample: 'rice',
    description: '魚や貝を水や白ワインなどで蒸し煮にした料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-ahijo',
    name: 'アヒージョ',
    category: 'other',
    aliases: ['あひーじょ'],
    sample: 'rice',
    description: '魚介や野菜などを、にんにく入りの油で煮た料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-fish-cake',
    name: 'かまぼこ・ちくわ',
    category: 'seafood',
    aliases: ['かまぼこ', 'ちくわ', '蒲鉾', '竹輪', 'はんぺん', 'さつま揚げ'],
    sample: 'rice',
    description: '魚のすり身を蒸す・焼く・揚げるなどした食品。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-fried-egg',
    name: '目玉焼き',
    category: 'egg_soy',
    aliases: ['めだまやき'],
    sample: 'rice',
    description: '卵を割り入れ、黄身を崩さずに焼いた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-rolled-omelet',
    name: '卵焼き',
    category: 'egg_soy',
    aliases: ['たまごやき', '玉子焼き', 'だし巻き卵', 'だしまきたまご', '厚焼き卵'],
    sample: 'rice',
    description: '溶いた卵を薄く焼き、巻き重ねた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-omelet',
    name: 'オムレツ',
    category: 'egg_soy',
    aliases: ['おむれつ'],
    sample: 'rice',
    description: '溶いた卵を焼き、折りたたむなどしてまとめた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-scrambled-eggs',
    name: 'スクランブルエッグ',
    category: 'egg_soy',
    aliases: ['すくらんぶるえっぐ', '炒り卵', 'いりたまご'],
    sample: 'rice',
    description: '溶いた卵をかき混ぜながら柔らかく焼いた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-boiled-egg',
    name: 'ゆで卵',
    category: 'egg_soy',
    aliases: ['ゆでたまご', '茹で卵', 'ゆで玉子', '煮卵', '味付け卵'],
    sample: 'rice',
    description: '殻ごとゆでた卵、または味を付けたゆで卵。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-onsen-egg',
    name: '温泉卵',
    category: 'egg_soy',
    aliases: ['おんせんたまご', '温玉', 'おんたま'],
    sample: 'rice',
    description: '白身と黄身を半熟に仕上げた卵。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-chawanmushi',
    name: '茶碗蒸し',
    category: 'egg_soy',
    aliases: ['ちゃわんむし'],
    sample: 'soup',
    description: 'だしを加えた卵液を、具材と一緒に蒸した料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-chilled-tofu',
    name: '冷ややっこ',
    category: 'egg_soy',
    aliases: ['ひややっこ', '冷奴', '冷や奴'],
    sample: 'rice',
    description: '冷たい豆腐に薬味やしょうゆなどを添えた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-tofu-steak',
    name: '豆腐ステーキ',
    category: 'egg_soy',
    aliases: ['とうふすてーき'],
    sample: 'rice',
    description: '豆腐の表面をこんがり焼いた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-agedashi-tofu',
    name: '揚げ出し豆腐',
    category: 'egg_soy',
    aliases: ['あげだしどうふ', '揚出し豆腐'],
    sample: 'rice',
    description: '粉をつけて揚げた豆腐に、だしをかけた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-mapo-tofu',
    name: '麻婆豆腐',
    category: 'egg_soy',
    aliases: ['まーぼーどうふ', 'マーボー豆腐', 'マーボーどうふ'],
    sample: 'rice',
    description: '豆腐を香辛料のきいたとろみのあるソースで煮た料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-natto',
    name: '納豆',
    category: 'egg_soy',
    aliases: ['なっとう'],
    sample: 'rice',
    description: '発酵させた大豆を、たれなどと混ぜて食べる食品。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-atsuage',
    name: '厚揚げ',
    category: 'egg_soy',
    aliases: ['あつあげ', '生揚げ', '厚揚げの煮物', '焼き厚揚げ'],
    sample: 'rice',
    description: '厚く切った豆腐を揚げたものや、その料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-shiraae',
    name: '白あえ',
    category: 'egg_soy',
    aliases: ['しらあえ', '白和え'],
    sample: 'rice',
    description: '豆腐をつぶしたあえ衣で具材をあえた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-iridofu',
    name: '炒り豆腐',
    category: 'egg_soy',
    aliases: ['いりどうふ', '炒りどうふ'],
    sample: 'rice',
    description: 'くずした豆腐を具材と一緒に炒めた料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-simmered-beans',
    name: '煮豆',
    category: 'egg_soy',
    aliases: ['にまめ', '大豆の煮物', '五目豆', '黒豆'],
    sample: 'rice',
    description: '大豆などの豆を柔らかく煮た料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-edamame',
    name: '枝豆',
    category: 'egg_soy',
    aliases: ['えだまめ'],
    sample: 'rice',
    description: '未熟な大豆を、さやごとゆでるなどして食べる料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-niratama',
    name: 'にら玉',
    category: 'egg_soy',
    aliases: ['にらたま', 'ニラ玉', '韮玉'],
    sample: 'rice',
    description: 'にらと卵を炒めたり、卵でとじたりした料理。',
    suggestedGroups: ['protein', 'vegetable'],
  },
  {
    id: 'generic-nikudofu',
    name: '肉豆腐',
    category: 'egg_soy',
    aliases: ['にくどうふ'],
    sample: 'rice',
    description: '肉と豆腐を甘辛い煮汁などで煮た料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-vegetable-stir-fry',
    name: '野菜炒め',
    category: 'vegetables',
    aliases: ['やさいいため'],
    sample: 'rice',
    description: '野菜を炒めて味付けした料理。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-vegetable-simmer',
    name: '野菜の煮物',
    category: 'vegetables',
    aliases: ['やさいのにもの', 'かぼちゃの煮物', '大根の煮物'],
    sample: 'soup',
    description: '野菜をだしや調味料で煮た料理。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-potato-salad',
    name: 'ポテトサラダ',
    category: 'vegetables',
    aliases: ['ぽてとさらだ', 'ポテサラ'],
    sample: 'rice',
    description: 'ゆでたじゃがいもをつぶし、具材や調味料とあえた料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-macaroni-salad',
    name: 'マカロニサラダ',
    category: 'vegetables',
    aliases: ['まかろにさらだ'],
    sample: 'rice',
    description: 'ゆでたマカロニに具材や調味料をあえた料理。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-coleslaw',
    name: 'コールスロー',
    category: 'vegetables',
    aliases: ['こーるすろー', 'キャベツサラダ'],
    sample: 'rice',
    description: '細く切ったキャベツなどをドレッシングであえた料理。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-ohitashi',
    name: 'おひたし',
    category: 'vegetables',
    aliases: ['お浸し', 'おしたし'],
    sample: 'rice',
    description: 'ゆでた青菜などをだしやしょうゆで味付けした料理。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-gomaae',
    name: 'ごまあえ',
    category: 'vegetables',
    aliases: ['ごまあえ', '胡麻和え', 'ごま和え'],
    sample: 'rice',
    description: '野菜などを、すりごま入りの衣であえた料理。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-namul',
    name: 'ナムル',
    category: 'vegetables',
    aliases: ['なむる'],
    sample: 'rice',
    description: '野菜をごま油などで味付けしたあえ物。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-sunomono',
    name: '酢の物',
    category: 'other',
    aliases: ['すのもの', '酢のもの'],
    sample: 'rice',
    description: '野菜や海藻、魚介などを合わせ酢であえた料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-kinpira',
    name: 'きんぴら',
    category: 'vegetables',
    aliases: ['きんぴらごぼう', '金平', 'きんぴら蓮根'],
    sample: 'rice',
    description: '細切りの根菜などを甘辛く炒めた料理。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-hijiki',
    name: 'ひじきの煮物',
    category: 'vegetables',
    aliases: ['ひじきのにもの', 'ひじき煮'],
    sample: 'rice',
    description: 'ひじきと具材を煮た料理。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-kiriboshi-daikon',
    name: '切り干し大根の煮物',
    category: 'vegetables',
    aliases: ['きりぼしだいこんのにもの', '切干大根', '切り干し大根'],
    sample: 'rice',
    description: '乾燥させた細切り大根を戻して煮た料理。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-pickles',
    name: '漬物',
    category: 'vegetables',
    aliases: ['つけもの', '漬け物', '浅漬け', 'ぬか漬け', 'たくあん'],
    sample: 'rice',
    description: '野菜を塩や調味液などに漬けた食品。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-kimchi',
    name: 'キムチ',
    category: 'vegetables',
    aliases: ['きむち', '白菜キムチ', 'カクテキ'],
    sample: 'rice',
    description: '白菜や大根などを唐辛子と漬けた食品。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-ratatouille',
    name: 'ラタトゥイユ',
    category: 'vegetables',
    aliases: ['らたとぅいゆ', 'ラタトゥーユ'],
    sample: 'soup',
    description: 'なすやトマトなどの野菜を煮込んだ料理。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-mapo-eggplant',
    name: '麻婆なす',
    category: 'vegetables',
    aliases: ['まーぼーなす', 'マーボーナス', '麻婆茄子'],
    sample: 'rice',
    description: 'なすを香辛料のきいたソースで炒め煮にした料理。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-tempura',
    name: '天ぷら',
    category: 'other',
    aliases: ['てんぷら', '天麩羅', '天婦羅', 'かき揚げ'],
    sample: 'rice',
    description: '魚介や野菜に薄い衣をつけて揚げた料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-pork-miso-soup',
    name: '豚汁',
    category: 'soup_hotpot',
    aliases: ['とんじる', 'ぶたじる'],
    sample: 'soup',
    description: '豚肉と具材を入れたみそ味の汁物。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-clear-soup',
    name: 'お吸い物',
    category: 'soup_hotpot',
    aliases: ['おすいもの', '吸い物', 'すまし汁'],
    sample: 'soup',
    description: 'だしを塩やしょうゆなどで調えた、澄んだ汁物。',
    suggestedGroups: [],
  },
  {
    id: 'generic-egg-soup',
    name: '卵スープ',
    category: 'soup_hotpot',
    aliases: ['たまごすーぷ', '玉子スープ', 'かきたま汁'],
    sample: 'soup',
    description: '溶き卵を流し入れたスープ。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-corn-soup',
    name: 'コーンスープ',
    category: 'soup_hotpot',
    aliases: ['こーんすーぷ', 'コーンポタージュ'],
    sample: 'soup',
    description: 'とうもろこしを使ったスープ。',
    suggestedGroups: [],
  },
  {
    id: 'generic-potage',
    name: 'ポタージュ',
    category: 'soup_hotpot',
    aliases: ['ぽたーじゅ', 'かぼちゃスープ', 'じゃがいもスープ'],
    sample: 'soup',
    description: '野菜などをなめらかにした、とろみのあるスープ。',
    suggestedGroups: [],
  },
  {
    id: 'generic-minestrone',
    name: 'ミネストローネ',
    category: 'soup_hotpot',
    aliases: ['みねすとろーね'],
    sample: 'soup',
    description: '野菜を細かく切って煮た、具だくさんのスープ。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-cream-stew',
    name: 'クリームシチュー',
    category: 'soup_hotpot',
    aliases: ['くりーむしちゅー', 'ホワイトシチュー', '白いシチュー'],
    sample: 'soup',
    description: '具材を白いクリームソースで煮込んだ料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-beef-stew',
    name: 'ビーフシチュー',
    category: 'soup_hotpot',
    aliases: ['びーふしちゅー'],
    sample: 'soup',
    description: '牛肉を洋風のソースで柔らかく煮込んだ料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-pot-au-feu',
    name: 'ポトフ',
    category: 'soup_hotpot',
    aliases: ['ぽとふ'],
    sample: 'soup',
    description: '大きめに切った野菜と肉類をスープで煮た料理。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-oden',
    name: 'おでん',
    category: 'soup_hotpot',
    aliases: ['御田'],
    sample: 'soup',
    description: '大根や練り物など、さまざまな具をだしで煮た料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-hotpot',
    name: '鍋料理',
    category: 'soup_hotpot',
    aliases: ['なべりょうり', '鍋', 'お鍋', '寄せ鍋', 'よせなべ'],
    sample: 'soup',
    description: '具材を一つの鍋で煮ながら食べる料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-sukiyaki',
    name: 'すき焼き',
    category: 'soup_hotpot',
    aliases: ['すきやき', '鋤焼き'],
    sample: 'soup',
    description: '肉や豆腐、野菜などを甘辛い味で煮る鍋料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-shabu-shabu',
    name: 'しゃぶしゃぶ',
    category: 'soup_hotpot',
    aliases: ['しゃぶしゃぶ鍋'],
    sample: 'soup',
    description: '薄切り肉などを熱いだしにくぐらせて食べる鍋料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-kimchi-hotpot',
    name: 'キムチ鍋',
    category: 'soup_hotpot',
    aliases: ['きむちなべ'],
    sample: 'soup',
    description: 'キムチと具材を一緒に煮る鍋料理。',
    suggestedGroups: ['vegetable'],
  },
  {
    id: 'generic-yudofu',
    name: '湯豆腐',
    category: 'soup_hotpot',
    aliases: ['ゆどうふ'],
    sample: 'soup',
    description: '豆腐をだしなどで温め、たれにつけて食べる料理。',
    suggestedGroups: ['protein'],
  },
  {
    id: 'generic-gratin',
    name: 'グラタン',
    category: 'other',
    aliases: ['ぐらたん'],
    sample: 'rice',
    description: '具材とソースを合わせ、表面に焼き色をつけた料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-fruit',
    name: '果物',
    category: 'sweets',
    aliases: ['くだもの', 'フルーツ', 'ふるーつ', 'カットフルーツ', 'フルーツ盛り合わせ'],
    sample: 'rice',
    description: '種類を問わない果物や、切り分けた果物。',
    suggestedGroups: ['fruit'],
  },
  {
    id: 'generic-banana',
    name: 'バナナ',
    category: 'sweets',
    aliases: ['ばなな'],
    sample: 'rice',
    description: '皮をむいて食べるバナナ。',
    suggestedGroups: ['fruit'],
  },
  {
    id: 'generic-apple',
    name: 'りんご',
    category: 'sweets',
    aliases: ['リンゴ', '林檎'],
    sample: 'rice',
    description: 'そのまま、または切って食べるりんご。',
    suggestedGroups: ['fruit'],
  },
  {
    id: 'generic-citrus',
    name: 'みかん・オレンジ',
    category: 'sweets',
    aliases: ['みかん', 'おれんじ', '蜜柑', 'オレンジ'],
    sample: 'rice',
    description: '皮をむいたり切り分けたりした、みかんやオレンジ。',
    suggestedGroups: ['fruit'],
  },
  {
    id: 'generic-berries',
    name: 'いちご・ベリー',
    category: 'sweets',
    aliases: ['いちご', 'べりー', 'イチゴ', '苺', 'ブルーベリー', 'ベリー'],
    sample: 'rice',
    description: 'いちごやブルーベリーなどの果物。',
    suggestedGroups: ['fruit'],
  },
  {
    id: 'generic-yogurt',
    name: 'ヨーグルト',
    category: 'sweets',
    aliases: ['よーぐると'],
    sample: 'rice',
    description: '発酵させた乳から作るヨーグルト。',
    suggestedGroups: ['dairy'],
  },
  {
    id: 'generic-cheese',
    name: 'チーズ',
    category: 'sweets',
    aliases: ['ちーず', 'プロセスチーズ', 'ナチュラルチーズ'],
    sample: 'rice',
    description: '乳を固めて作ったチーズ。',
    suggestedGroups: ['dairy'],
  },
  {
    id: 'generic-pudding',
    name: 'プリン',
    category: 'sweets',
    aliases: ['ぷりん', 'カスタードプリン'],
    sample: 'rice',
    description: '卵液などを固めた、柔らかいデザート。',
    suggestedGroups: [],
  },
  {
    id: 'generic-jelly',
    name: 'ゼリー',
    category: 'sweets',
    aliases: ['ぜりー', 'フルーツゼリー', '寒天ゼリー'],
    sample: 'rice',
    description: '果汁などの液体を固めたデザート。',
    suggestedGroups: [],
  },
  {
    id: 'generic-ice-cream',
    name: 'アイスクリーム',
    category: 'sweets',
    aliases: ['あいすくりーむ', 'アイス', 'ソフトクリーム'],
    sample: 'rice',
    description: '冷やし固めた、なめらかなデザート。',
    suggestedGroups: [],
  },
  {
    id: 'generic-cake',
    name: 'ケーキ',
    category: 'sweets',
    aliases: ['けーき', 'ショートケーキ', 'チョコレートケーキ', 'チーズケーキ'],
    sample: 'rice',
    description: '生地やクリームなどを組み合わせた洋菓子。',
    suggestedGroups: [],
  },
  {
    id: 'generic-cookies',
    name: 'クッキー・ビスケット',
    category: 'sweets',
    aliases: ['くっきー', 'びすけっと', 'クッキー', 'ビスケット'],
    sample: 'rice',
    description: '小さく成形した生地を焼いた菓子。',
    suggestedGroups: [],
  },
  {
    id: 'generic-doughnut',
    name: 'ドーナツ',
    category: 'sweets',
    aliases: ['どーなつ', 'ドーナッツ'],
    sample: 'rice',
    description: '甘い生地を揚げたり焼いたりした菓子。',
    suggestedGroups: [],
  },
  {
    id: 'generic-crepe',
    name: 'クレープ',
    category: 'sweets',
    aliases: ['くれーぷ'],
    sample: 'rice',
    description: '薄く焼いた生地でクリームや具材などを包んだ料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-cream-puff',
    name: 'シュークリーム',
    category: 'sweets',
    aliases: ['しゅーくりーむ'],
    sample: 'rice',
    description: '空洞のある生地にクリームを詰めた洋菓子。',
    suggestedGroups: [],
  },
  {
    id: 'generic-dango',
    name: '団子',
    category: 'sweets',
    aliases: ['だんご', 'だんごもち', 'みたらし団子', '三色団子'],
    sample: 'rice',
    description: '米粉などを練って丸め、蒸す・ゆでるなどした菓子。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-daifuku',
    name: '大福',
    category: 'sweets',
    aliases: ['だいふく', '大福餅', '豆大福'],
    sample: 'rice',
    description: 'あんなどを柔らかい餅で包んだ和菓子。',
    suggestedGroups: ['staple'],
  },
  {
    id: 'generic-taiyaki',
    name: 'たい焼き',
    category: 'sweets',
    aliases: ['たいやき', '鯛焼き'],
    sample: 'rice',
    description: '魚の形の生地であんなどを包んで焼いた菓子。',
    suggestedGroups: [],
  },
  {
    id: 'generic-yokan',
    name: 'ようかん',
    category: 'sweets',
    aliases: ['羊羹'],
    sample: 'rice',
    description: 'あんなどを寒天などで固めた和菓子。',
    suggestedGroups: [],
  },
  {
    id: 'generic-roasted-sweet-potato',
    name: '焼きいも・ふかしいも',
    category: 'sweets',
    aliases: ['やきいも', '焼きいも', '焼き芋', 'ふかしいも'],
    sample: 'rice',
    description: 'さつまいもを焼いたり蒸したりした料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-happosai',
    name: '八宝菜',
    category: 'other',
    aliases: ['はっぽうさい', '八寶菜'],
    sample: 'rice',
    description: '野菜や肉、魚介などを炒め、とろみをつけた料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-fried-food',
    name: '揚げ物',
    category: 'other',
    aliases: ['あげもの', '揚げもの'],
    sample: 'rice',
    description: '肉や魚、野菜などを油で揚げた料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-steamed-food',
    name: '蒸し料理',
    category: 'other',
    aliases: ['むしりょうり', '蒸し物', 'むしもの'],
    sample: 'rice',
    description: '肉や魚、野菜などを蒸して火を通した料理。',
    suggestedGroups: [],
  },
  {
    id: 'generic-aemono',
    name: 'あえ物',
    category: 'other',
    aliases: ['あえもの', '和え物', '和えもの'],
    sample: 'rice',
    description: '野菜や魚介などの具材を、調味料やあえ衣であえた料理。',
    suggestedGroups: [],
  },
]

export function genericDishById(id?: string): GenericDish | undefined {
  return genericDishes.find((dish) => dish.id === id)
}
